# [Optional] Custom Dockerfile for Vue.js Dev Container
FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Copy all files from the current directory to the container
COPY . /workspace

# Set working directory
WORKDIR /workspace
